const $=s=>document.querySelector(s),conversation=$("#conversation"),question=$("#question");
const sessionId=localStorage.getItem("rag-session")||crypto.randomUUID();localStorage.setItem("rag-session",sessionId);
const escapeHtml=value=>{const node=document.createElement("div");node.textContent=value;return node.innerHTML};
function addMessage(role,text,result=null){$("#empty")?.remove();const article=document.createElement("article");article.className=`message ${role}`;if(role==="user")article.textContent=text;else{article.innerHTML=`<div class="answer">${escapeHtml(text)}</div>`;if(result){article.innerHTML+=`<div class="meta">Confidence ${Math.round(result.confidence*100)}% · ${result.sources.length} sources</div>`;const sources=document.createElement("div");sources.className="sources";result.sources.forEach(s=>sources.innerHTML+=`<details class="source"><summary>[${s.citation}] ${escapeHtml(s.source)} · page ${s.page} · ${Math.round(s.score*100)}%</summary><p>${escapeHtml(s.preview)}…</p></details>`);article.appendChild(sources)}}conversation.appendChild(article);article.scrollIntoView({behavior:"smooth",block:"end"});return article}
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options}),data=await response.json();if(!response.ok)throw new Error(data.detail||"Request failed");return data}
async function checkStatus(){const data=await api("/api/status"),status=$("#status");status.classList.toggle("ready",data.ready);status.lastChild.textContent=data.ready?" Ready":data.indexed?" Model unavailable":" Index required";$("#threshold").value=data.default_threshold;$("#thresholdValue").value=`${Math.round(data.default_threshold*100)}%`}
$("#threshold").addEventListener("input",e=>$("#thresholdValue").value=`${Math.round(e.target.value*100)}%`);
$("#chatForm").addEventListener("submit",async e=>{e.preventDefault();const text=question.value.trim();if(!text)return;addMessage("user",text);question.value="";const loading=addMessage("assistant","Searching and reranking…");loading.classList.add("loading");$("#send").disabled=true;try{const result=await api("/api/chat",{method:"POST",body:JSON.stringify({question:text,session_id:sessionId,threshold:Number($("#threshold").value)})});loading.remove();addMessage("assistant",result.answer,result)}catch(error){loading.querySelector(".answer").textContent=error.message;loading.classList.remove("loading")}finally{$("#send").disabled=false;question.focus()}});
question.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#chatForm").requestSubmit()}});
document.querySelectorAll(".suggestions button").forEach(b=>b.addEventListener("click",()=>{question.value=b.textContent;$("#chatForm").requestSubmit()}));
$("#clear").addEventListener("click",async()=>{await api("/api/clear",{method:"POST",body:JSON.stringify({session_id:sessionId})});location.reload()});
$("#reindex").addEventListener("click",async e=>{e.target.disabled=true;e.target.textContent="Indexing…";try{const s=await api("/api/reindex",{method:"POST"});alert(`Indexed ${s.documents} document units into ${s.chunks} chunks.`);await checkStatus()}catch(error){alert(error.message)}finally{e.target.disabled=false;e.target.textContent="Rebuild index"}});checkStatus().catch(()=>$("#status").lastChild.textContent=" API unavailable");

